repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        exclude: '(^notebooks/|^data/|^models/|^reports/|^\.venv/|^docker/)'
      - id: ruff-format
        exclude: '(^notebooks/|^data/|^models/|^reports/|^\.venv/|^docker/)'

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100", "--fast"]
        files: '\.py$'
        exclude: '(^notebooks/|^data/|^models/|^reports/|^\.venv/|^docker/)'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        files: '^(src/|app/)'
        exclude: '(^notebooks/|^data/|^models/|^reports/|^\.venv/|^docker/)'
