[tool.black]
line-length = 100
target-version = ["py311"]
extend-exclude = "notebooks|data|models|reports|\\.venv|\\.git|docker"

[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = ["I"]
extend-exclude = ["notebooks", "data", "models", "reports", ".venv", ".git", "docker"]
# no fixes automáticos en CI
fix = false

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
pretty = true
exclude = "(^notebooks/|^data/|^models/|^reports/|^\\.venv/|^docker/)"
