[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = ["I"]          # isort (orden de imports)
ignore = ["D100","D104"]       # docstrings en módulos vacíos si te molestan
fix = true

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true
no_implicit_optional = true
check_untyped_defs = true
disallow_untyped_defs = false   # en V1 no obligamos tipos en todas las funcs
exclude = ["tests/.*", "notebooks/.*"]
